// flow-typed signature: 7d69bdd42e94cf96a67fbdb0e4416a46
// flow-typed version: <<STUB>>/Promise_v1.0.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'Promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'Promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'Promise/lib/Promise' {
  declare module.exports: any;
}

declare module 'Promise/lib/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'Promise/lib/Promise.js' {
  declare module.exports: $Exports<'Promise/lib/Promise'>;
}
declare module 'Promise/lib/test/main.js' {
  declare module.exports: $Exports<'Promise/lib/test/main'>;
}
