// flow-typed signature: a6694762271e7e092f458889e2d477d2
// flow-typed version: <<STUB>>/winston-elasticsearch_v0.7.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-elasticsearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-elasticsearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-elasticsearch/bulk_writer' {
  declare module.exports: any;
}

declare module 'winston-elasticsearch/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-elasticsearch/bulk_writer.js' {
  declare module.exports: $Exports<'winston-elasticsearch/bulk_writer'>;
}
declare module 'winston-elasticsearch/index' {
  declare module.exports: $Exports<'winston-elasticsearch'>;
}
declare module 'winston-elasticsearch/index.js' {
  declare module.exports: $Exports<'winston-elasticsearch'>;
}
declare module 'winston-elasticsearch/transformer.js' {
  declare module.exports: $Exports<'winston-elasticsearch/transformer'>;
}
